<h1 style="color: #7A1FA2; text-align: center; margin: 0;">ARMADO DEL DATASET CRUDO</h1>

In [24]:
# Otra forma de verificar el entorno de trabajo activo
# El entorno de trabajo activo figurará con un *

!conda env list

# conda environments:
#
# * -> active
# + -> frozen
base                     C:\Users\Arturo\anaconda3
envml                    C:\Users\Arturo\anaconda3\envs\envml
envml_nuevo          *   C:\Users\Arturo\anaconda3\envs\envml_nuevo

In [25]:
# Se configuran opciones de visualización para mostrar todas las columnas y filas

import pandas as pd

pd.set_option('display.max_columns', None)  # Mostrar todas las columnas
pd.set_option('display.max_rows', None)     # Mostrar todas las filas

In [26]:
import pandas as pd

path_dinacea_crudo = './0-Datasets/SL_CA_DINACEA_2011_2025.xlsx'

raw = pd.read_excel(path_dinacea_crudo, sheet_name=0, header=None)

# Fila 0: nombre de variable (viene con celdas combinadas => hay que "rellenar hacia la derecha")
vars_ = raw.iloc[0, 1:].ffill()

# Fila 1: estaciones/códigos
stations = raw.iloc[1, 1:]

# Datos: desde la fila 3 en adelante (0=vars, 1=station, 2=date)
data = raw.iloc[3:, 1:]

# Índice fecha: columna 0 desde la fila 3
dates = pd.to_datetime(raw.iloc[3:, 0], errors="coerce")

# Armar DataFrame limpio con columnas MultiIndex
data_dinacea_crudo = data.copy()
data_dinacea_crudo.index = dates
data_dinacea_crudo.index.name = "date"
data_dinacea_crudo.columns = pd.MultiIndex.from_arrays([vars_, stations], names=["variable", "station"])

# Convertir a numérico (por si hay strings sueltos)
data_dinacea_crudo = data_dinacea_crudo.apply(pd.to_numeric, errors="coerce")

data_dinacea_crudo.head()

variable   Fósforo Total (PT) [μg/L]                                          \
station                      XSJO030 XCOL010 XSLU050 XCAG040 XSLU040 XCAH020
date
2011-01-31                       NaN   250.0   735.0  1200.0   703.0  9300.0
2011-02-28                       NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31                     531.0   290.0   183.0   483.0   258.0   612.0
2011-04-30                       NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31                     370.0   286.0  1060.0   149.0   139.0     NaN

variable                                                                    \
station    XSLU030 XSLH020 XSLH030 XSLU010 XSJO010 XSJO020 XSJO040 XCGA050
date
2011-01-31   591.0   406.0   911.0   634.0   240.0   299.0   420.0  2900.0
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31   135.0   404.0   750.0   294.0    68.0   216.0   430.0  2890.0
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31    97.7   289.0   319.0   181.0   247.0   148.0   302.0   609.0

variable                                                                    \
station    XSLU060 XSLH010 EPSE030 EPSE040 EPSE020 XCPA020 XCAH010 XCAG010
date
2011-01-31   341.0    85.6   332.0   324.0   338.0   526.0   384.0   662.0
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31   326.0    91.1   349.0   345.0   361.0    80.5   593.0   649.0
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   345.0    56.1   278.0   277.0   273.0    78.4   644.0   514.0

variable                            Nitrógeno Total (NT) [mg/L]          \
station     ECAG030 ECAG020 XVIR050                     XSJO030 XCOL010
date
2011-01-31    622.0     NaN     NaN                         NaN     NaN
2011-02-28      NaN     NaN     NaN                         NaN     NaN
2011-03-31  12900.0     NaN     NaN                         NaN     NaN
2011-04-30      NaN     NaN     NaN                         NaN     NaN
2011-05-31    742.0     NaN     NaN                         NaN     NaN

variable                                                                    \
station    XSLU050 XCAG040 XSLU040 XCAH020 XSLU030 XSLH020 XSLH030 XSLU010
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                                                    \
station    XSJO010 XSJO020 XSJO040 XCGA050 XSLU060 XSLH010 EPSE030 EPSE040
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                                            \
station    EPSE020 XCPA020 XCAH010 XCAG010 ECAG030 ECAG020 XVIR050
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable   Ion Nitrato (NO3-) [mg/L]                                          \
station                      XSJO030 XCOL010 XSLU050 XCAG040 XSLU040 XCAH020
date
2011-01-31                       NaN   0.014    0.24    0.85   0.014   6.975
2011-02-28                       NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31                      0.09   0.250    0.15    0.34   0.090   1.240
2011-04-30                       NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31                      0.64   0.440    0.57    0.19   0.035   0.035

variable                                                                    \
station    XSLU030 XSLH020 XSLH030 XSLU010 XSJO010 XSJO020 XSJO040 XCGA050
date
2011-01-31   0.014   0.035    1.60   0.014   0.035   0.035   0.084    1.30
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31   0.090   0.100    0.90   0.090   0.100   0.100   0.140    0.14
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   0.035   0.350    0.98   0.520   0.220   0.150   0.510   15.00

variable                                                                    \
station    XSLU060 XSLH010 EPSE030 EPSE040 EPSE020 XCPA020 XCAH010 XCAG010
date
2011-01-31    0.25   0.035    0.37    0.39    0.35   0.014   0.035   0.035
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31    0.10   0.110    0.31    0.29    0.39   0.110   0.200   0.090
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31    0.46   0.035    0.69    0.64    0.86   0.180   0.014   0.035

variable                           Ion Nitrito (NO2-) [mg/L]                  \
station    ECAG030 ECAG020 XVIR050                   XSJO030 XCOL010 XSLU050
date
2011-01-31   0.242     NaN     NaN                       NaN   0.003   0.003
2011-02-28     NaN     NaN     NaN                       NaN     NaN     NaN
2011-03-31   0.310     NaN     NaN                     0.002   0.033   0.018
2011-04-30     NaN     NaN     NaN                       NaN     NaN     NaN
2011-05-31   0.390     NaN     NaN                     0.039   0.039   0.370

variable                                                                    \
station    XCAG040 XSLU040 XCAH020 XSLU030 XSLH020 XSLH030 XSLU010 XSJO010
date
2011-01-31   0.058   0.001     NaN   0.001   0.001   0.150   0.001   0.003
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31   0.010   0.002     NaN   0.014   0.010   0.212   0.009   0.002
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   0.039   0.039     2.6   0.039   0.039   0.039   0.039   0.039

variable                                                                    \
station    XSJO020 XSJO040 XCGA050 XSLU060 XSLH010 EPSE030 EPSE040 EPSE020
date
2011-01-31   0.003   0.003   0.045   0.003   0.003   0.003   0.003   0.008
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31   0.002   0.002   0.002   0.002   0.058   0.009   0.002   0.002
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   0.100   0.039   0.039   0.039   0.039   0.039   0.039   0.039

variable                                                    \
station    XCPA020 XCAH010 XCAG010 ECAG030 ECAG020 XVIR050
date
2011-01-31   0.001   0.016   0.007   0.003     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31   0.002   0.059   0.006   0.006     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   0.039   0.100   0.039   0.390     NaN     NaN

variable   Ion Amonio (NH4+) [mg/L]                                          \
station                     XSJO030 XCOL010 XSLU050 XCAG040 XSLU040 XCAH020
date
2011-01-31                      NaN   0.007    0.01   0.081   0.007    15.0
2011-02-28                      NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31                    0.070   0.010    0.04   0.010   0.040    26.0
2011-04-30                      NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31                    0.029   0.520    0.45   0.034   0.010    62.0

variable                                                                    \
station    XSLU030 XSLH020 XSLH030 XSLU010 XSJO010 XSJO020 XSJO040 XCGA050
date
2011-01-31   0.007   0.010    0.31    0.01    0.01   0.036   0.010   0.085
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31   0.050   0.120    0.49    0.24    0.02   0.010   0.010   0.010
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   0.010   0.022    0.14    0.06    0.02   0.010   0.038   0.010

variable                                                                    \
station    XSLU060 XSLH010 EPSE030 EPSE040 EPSE020 XCPA020 XCAH010 XCAG010
date
2011-01-31   0.007   0.022    0.01    0.01   0.010   0.010   0.007   0.043
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31   0.010   0.150    0.02    0.01   0.060   0.110   0.039   0.071
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   0.035   0.010    0.01    0.01   0.043   0.021   0.010   0.058

variable                           Ion Fosfato (PO4-) [µg/L]                  \
station    ECAG030 ECAG020 XVIR050                   XSJO030 XCOL010 XSLU050
date
2011-01-31   0.007     NaN     NaN                       NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN                       NaN     NaN     NaN
2011-03-31   0.010     NaN     NaN                       NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN                       NaN     NaN     NaN
2011-05-31   0.140     NaN     NaN                       NaN     NaN     NaN

variable                                                                    \
station    XCAG040 XSLU040 XCAH020 XSLU030 XSLH020 XSLH030 XSLU010 XSJO010
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                                                    \
station    XSJO020 XSJO040 XCGA050 XSLU060 XSLH010 EPSE030 EPSE040 EPSE020
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                                   Glifosato [µg/L]  \
station    XCPA020 XCAH010 XCAG010 ECAG030 ECAG020 XVIR050          XSJO030
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN              NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN              NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN              NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN              NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN              NaN

variable                                                                    \
station    XCOL010 XSLU050 XCAG040 XSLU040 XCAH020 XSLU030 XSLH020 XSLH030
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                                                    \
station    XSLU010 XSJO010 XSJO020 XSJO040 XCGA050 XSLU060 XSLH010 EPSE030
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                                                    \
station    EPSE040 EPSE020 XCPA020 XCAH010 XCAG010 ECAG030 ECAG020 XVIR050
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable   Solidos totales (ST) [mg/L]                                  \
station                        XSJO030 XCOL010 XSLU050 XCAG040 XSLU040
date
2011-01-31                         NaN     NaN     NaN     NaN     NaN
2011-02-28                         NaN     NaN     NaN     NaN     NaN
2011-03-31                         NaN     NaN     NaN     NaN     NaN
2011-04-30                         NaN     NaN     NaN     NaN     NaN
2011-05-31                         NaN     NaN     NaN     NaN     NaN

variable                                                                    \
station    XCAH020 XSLU030 XSLH020 XSLH030 XSLU010 XSJO010 XSJO020 XSJO040
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                                                    \
station    XCGA050 XSLU060 XSLH010 EPSE030 EPSE040 EPSE020 XCPA020 XCAH010
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                    \
station    XCAG010 ECAG030 ECAG020 XVIR050
date
2011-01-31     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN

variable   Solidos suspendidos totales (SST) [mg/L]                          \
station                                     XSJO030 XCOL010 XSLU050 XCAG040
date
2011-01-31                                      NaN     NaN     NaN     NaN
2011-02-28                                      NaN     NaN     NaN     NaN
2011-03-31                                      NaN     NaN     NaN     NaN
2011-04-30                                      NaN     NaN     NaN     NaN
2011-05-31                                      NaN     NaN     NaN     NaN

variable                                                                    \
station    XSLU040 XCAH020 XSLU030 XSLH020 XSLH030 XSLU010 XSJO010 XSJO020
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                                                    \
station    XSJO040 XCGA050 XSLU060 XSLH010 EPSE030 EPSE040 EPSE020 XCPA020
date
2011-01-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

variable                                           Turbidez [NTU]          \
station    XCAH010 XCAG010 ECAG030 ECAG020 XVIR050        XSJO030 XCOL010
date
2011-01-31     NaN     NaN     NaN     NaN     NaN            NaN     5.3
2011-02-28     NaN     NaN     NaN     NaN     NaN            NaN     NaN
2011-03-31     NaN     NaN     NaN     NaN     NaN           20.0     6.2
2011-04-30     NaN     NaN     NaN     NaN     NaN            NaN     NaN
2011-05-31     NaN     NaN     NaN     NaN     NaN           34.0    14.0

variable                                                                    \
station    XSLU050 XCAG040 XSLU040 XCAH020 XSLU030 XSLH020 XSLH030 XSLU010
date
2011-01-31    10.0    40.0     3.8    33.3     6.2    17.0     8.4     4.8
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     5.5    99.0     4.2    30.0     4.5     4.8    21.0     4.4
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   120.0     3.6     3.8    31.0     5.7    18.0    21.0     4.4

variable                                                                    \
station    XSJO010 XSJO020 XSJO040 XCGA050 XSLU060 XSLH010 EPSE030 EPSE040
date
2011-01-31    2.90     3.6    25.0    61.0    11.0    12.0    10.0    10.0
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31    1.81     8.3    14.0    95.0    15.0    17.0    11.0     8.9
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31   32.00    25.0    22.0    18.0    20.0     8.2    13.0    12.0

variable                                                            \
station    EPSE020 XCPA020 XCAH010 XCAG010 ECAG030 ECAG020 XVIR050
date
2011-01-31    11.0     2.8    45.3     5.5    80.0     NaN     NaN
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31    17.0     5.5    29.0    10.0   110.0     NaN     NaN
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31    17.0    13.0    28.0     2.3   130.0     NaN     NaN

variable   Temperatura del agua (T) [ºC]                                  \
station                          XSJO030 XCOL010 XSLU050 XCAG040 XSLU040
date
2011-01-31                           NaN    25.0    27.4    25.6    26.9
2011-02-28                           NaN     NaN     NaN     NaN     NaN
2011-03-31                          21.5    22.8    21.8    20.1    22.1
2011-04-30                           NaN     NaN     NaN     NaN     NaN
2011-05-31                          14.6    15.3    12.2    14.5    16.9

variable                                                                    \
station    XCAH020 XSLU030 XSLH020 XSLH030 XSLU010 XSJO010 XSJO020 XSJO040
date
2011-01-31    20.0    26.0    21.4    25.3    24.4    23.6    25.9    27.6
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31    20.1    21.4    21.0    23.4    21.2    17.6    21.1    22.4
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31    11.4    15.4    11.9    13.0    14.7    12.9    14.1    15.5

variable                                                                    \
station    XCGA050 XSLU060 XSLH010 EPSE030 EPSE040 EPSE020 XCPA020 XCAH010
date
2011-01-31    22.7    27.2    21.4    25.1    26.2    24.7    22.8    26.9
2011-02-28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31    20.7    18.2    20.9    22.6    24.3    21.5    20.8    22.0
2011-04-30     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31    14.2    12.3    12.8    16.0    17.0    13.5    13.5    11.6

variable                                   Oxigeno Disuelto (OD) [mg/L]  \
station    XCAG010 ECAG030 ECAG020 XVIR050                      XSJO030

In [27]:
# Se seleccionan del dataset de calidad de agua las estaciones ubicadas en la cuenca de Paso Severino

cols = ["EPSE020", "EPSE040", "EPSE030", "XSLH030", "XSLH020", "XSLH010"]
data_dinacea_crudo = data_dinacea_crudo.loc[:, data_dinacea_crudo.columns.get_level_values(1).isin(cols)].copy()

data_dinacea_crudo.head()

variable   Fósforo Total (PT) [μg/L]                                          \
station                      XSLH020 XSLH030 XSLH010 EPSE030 EPSE040 EPSE020
date
2011-01-31                     406.0   911.0    85.6   332.0   324.0   338.0
2011-02-28                       NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31                     404.0   750.0    91.1   349.0   345.0   361.0
2011-04-30                       NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31                     289.0   319.0    56.1   278.0   277.0   273.0

variable   Nitrógeno Total (NT) [mg/L]                                  \
station                        XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2011-01-31                         NaN     NaN     NaN     NaN     NaN
2011-02-28                         NaN     NaN     NaN     NaN     NaN
2011-03-31                         NaN     NaN     NaN     NaN     NaN
2011-04-30                         NaN     NaN     NaN     NaN     NaN
2011-05-31                         NaN     NaN     NaN     NaN     NaN

variable           Ion Nitrato (NO3-) [mg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2011-01-31     NaN                     0.035    1.60   0.035    0.37    0.39
2011-02-28     NaN                       NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN                     0.100    0.90   0.110    0.31    0.29
2011-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN                     0.350    0.98   0.035    0.69    0.64

variable           Ion Nitrito (NO2-) [mg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2011-01-31    0.35                     0.001   0.150   0.003   0.003   0.003
2011-02-28     NaN                       NaN     NaN     NaN     NaN     NaN
2011-03-31    0.39                     0.010   0.212   0.058   0.009   0.002
2011-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
2011-05-31    0.86                     0.039   0.039   0.039   0.039   0.039

variable           Ion Amonio (NH4+) [mg/L]                                  \
station    EPSE020                  XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2011-01-31   0.008                    0.010    0.31   0.022    0.01    0.01
2011-02-28     NaN                      NaN     NaN     NaN     NaN     NaN
2011-03-31   0.002                    0.120    0.49   0.150    0.02    0.01
2011-04-30     NaN                      NaN     NaN     NaN     NaN     NaN
2011-05-31   0.039                    0.022    0.14   0.010    0.01    0.01

variable           Ion Fosfato (PO4-) [µg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2011-01-31   0.010                       NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN                       NaN     NaN     NaN     NaN     NaN
2011-03-31   0.060                       NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
2011-05-31   0.043                       NaN     NaN     NaN     NaN     NaN

variable           Glifosato [µg/L]                                          \
station    EPSE020          XSLH020 XSLH030 XSLH010 EPSE030 EPSE040 EPSE020
date
2011-01-31     NaN              NaN     NaN     NaN     NaN     NaN     NaN
2011-02-28     NaN              NaN     NaN     NaN     NaN     NaN     NaN
2011-03-31     NaN              NaN     NaN     NaN     NaN     NaN     NaN
2011-04-30     NaN              NaN     NaN     NaN     NaN     NaN     NaN
2011-05-31     NaN              NaN     NaN     NaN     NaN     NaN     NaN

variable   Solidos totales (ST) [mg/L]                                  \
station                        XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2011-01-31                         NaN     NaN     NaN     NaN     NaN
2011-02-28                         NaN     NaN     NaN     NaN     NaN
2011-03-31                         NaN     NaN     NaN     NaN     NaN
2011-04-30                         NaN     NaN     NaN     NaN     NaN
2011-05-31                         NaN     NaN     NaN     NaN     NaN

variable           Solidos suspendidos totales (SST) [mg/L]                  \
station    EPSE020                                  XSLH020 XSLH030 XSLH010
date
2011-01-31     NaN                                      NaN     NaN     NaN
2011-02-28     NaN                                      NaN     NaN     NaN
2011-03-31     NaN                                      NaN     NaN     NaN
2011-04-30     NaN                                      NaN     NaN     NaN
2011-05-31     NaN                                      NaN     NaN     NaN

variable                           Turbidez [NTU]                          \
station    EPSE030 EPSE040 EPSE020        XSLH020 XSLH030 XSLH010 EPSE030
date
2011-01-31     NaN     NaN     NaN           17.0     8.4    12.0    10.0
2011-02-28     NaN     NaN     NaN            NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN     NaN            4.8    21.0    17.0    11.0
2011-04-30     NaN     NaN     NaN            NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN     NaN           18.0    21.0     8.2    13.0

variable                   Temperatura del agua (T) [ºC]                  \
station    EPSE040 EPSE020                       XSLH020 XSLH030 XSLH010
date
2011-01-31    10.0    11.0                          21.4    25.3    21.4
2011-02-28     NaN     NaN                           NaN     NaN     NaN
2011-03-31     8.9    17.0                          21.0    23.4    20.9
2011-04-30     NaN     NaN                           NaN     NaN     NaN
2011-05-31    12.0    17.0                          11.9    13.0    12.8

variable                           Oxigeno Disuelto (OD) [mg/L]          \
station    EPSE030 EPSE040 EPSE020                      XSLH020 XSLH030
date
2011-01-31    25.1    26.2    24.7                         5.96    4.55
2011-02-28     NaN     NaN     NaN                          NaN     NaN
2011-03-31    22.6    24.3    21.5                         5.45    5.10
2011-04-30     NaN     NaN     NaN                          NaN     NaN
2011-05-31    16.0    17.0    13.5                         7.42    5.52

variable                                    \
station    XSLH010 EPSE030 EPSE040 EPSE020
date
2011-01-31    4.38    7.00    6.95    6.69
2011-02-28     NaN     NaN     NaN     NaN
2011-03-31    5.24    6.55    7.12    6.54
2011-04-30     NaN     NaN     NaN     NaN
2011-05-31    7.63    8.00    7.88    7.87

variable   Demanda Bioquímica de Oxigeno (DBO) [mg/L]                          \
station                                       XSLH020 XSLH030 XSLH010 EPSE030
date
2011-01-31                                        2.2     3.9     1.0     NaN
2011-02-28                                        NaN     NaN     NaN     NaN
2011-03-31                                        1.5    12.0     1.9     NaN
2011-04-30                                        NaN     NaN     NaN     NaN
2011-05-31                                        1.0     2.3     1.0     NaN

variable                   Clorofila-a (Chl-a) [μg/L]                          \
station    EPSE040 EPSE020                    XSLH020 XSLH030 XSLH010 EPSE030
date
2011-01-31     NaN     NaN                        NaN   27.40     NaN     2.5
2011-02-28     NaN     NaN                        NaN     NaN     NaN     NaN
2011-03-31     NaN     NaN                        NaN    0.05     NaN     1.5
2011-04-30     NaN     NaN                        NaN     NaN     NaN     NaN
2011-05-31     NaN     NaN                        NaN    0.30     NaN     3.0

variable                   Potencial de Hidrogeno (pH) [NA]                  \
station    EPSE040 EPSE020                          XSLH020 XSLH030 XSLH010
date
2011-01-31    1.90     2.4                             7.31    7.37    7.31
2011-02-28     NaN     NaN                              NaN     NaN     NaN
2011-03-31    2.10     4.6                             7.89    7.95    7.54
2011-04-30     NaN     NaN                              NaN     NaN     NaN
2011-05-31    0.05     0.3                             7.43    7.37    7.50

variable                           Conductividad [μS/cm]                  \
station    EPSE030 EPSE040 EPSE020               XSLH020 XSLH030 XSLH010
date
2011-01-31    7.89    7.87    7.88                 328.4   518.0   432.8
2011-02-28     NaN     NaN     NaN                   NaN     NaN     NaN
2011-03-31    7.76    7.71    7.58                 426.3   595.0   373.7
2011-04-30     NaN     NaN     NaN                   NaN     NaN     NaN
2011-05-31    7.73    7.63    7.61                 226.2   253.2   266.0

variable
station    EPSE030 EPSE040 EPSE020
date
2011-01-31   283.3   219.7   293.4
2011-02-28     NaN     NaN     NaN
2011-03-31   294.4   302.8   297.4
2011-04-30     NaN     NaN     NaN
2011-05-31   276.1   272.0   295.0

In [28]:
import pandas as pd

# lectura del dataset crudo de DINAGUA
path_dinagua_crudo = './0-Datasets/SL_HIDRO_DINAGUA_1980_2025.xlsx'
raw = pd.read_excel(path_dinagua_crudo, sheet_name=0, header=None)

# detectar filas "station" y "date" (en la primera columna)
col0 = raw.iloc[:, 0].astype(str).str.strip().str.lower()
station_row = col0[col0.eq("station")].index[0]
date_row    = col0[col0.eq("date")].index[0]

# asumimos que la fila anterior a "station" contiene el "grupo/variable" (celdas combinadas -> ffill)
var_row = station_row - 1

vars_ = raw.iloc[var_row, 1:].astype(str).str.strip()
vars_ = vars_.replace({"nan": None, "None": None}).ffill()

stations = raw.iloc[station_row, 1:].astype(str).str.strip()

# los datos empiezan después de la fila "date"
data_start = date_row + 1

dates = pd.to_datetime(raw.iloc[data_start:, 0], errors="coerce")
data  = raw.iloc[data_start:, 1:]

data_dinagua_crudo = data.copy()
data_dinagua_crudo.index = dates
data_dinagua_crudo.index.name = "date"

data_dinagua_crudo.columns = pd.MultiIndex.from_arrays(
    [vars_, stations],
    names=["variable", "station"]
)

# convertir a numérico
data_dinagua_crudo = data_dinagua_crudo.apply(pd.to_numeric, errors="coerce")

data_dinagua_crudo.head()

variable     Caudal (Q) [m3/s]                          \
station    Fray Marcos DINAGUA Florida (Puente Ruta 5)
date
1980-01-01               7.978                     0.0
1980-01-02               7.978                     0.0
1980-01-03               7.978                     0.0
1980-01-04               7.978                     0.0
1980-01-05               7.978                     0.0

variable                                                           \
station    Paso Pache (Ruta 5 nueva) Picada de Varela Paso Roldan
date
1980-01-01                       NaN              NaN       0.359
1980-01-02                       NaN              NaN       0.359
1980-01-03                       NaN              NaN       0.359
1980-01-04                       NaN              NaN       0.318
1980-01-05                       NaN              NaN       0.318

variable                                             Nivel de agua (h) [m]  \
station    Paso de los Troncos Santa Lucia (Ruta 11)           Fray Marcos
date
1980-01-01               0.959                 1.738                   NaN
1980-01-02               0.959                 1.738                   NaN
1980-01-03               0.959                 1.738                   NaN
1980-01-04               0.959                 1.738                   NaN
1980-01-05               0.959                 1.738                   NaN

variable                                                      \
station    Florida (Puente Ruta 5) Paso Pache (Ruta 5 nueva)
date
1980-01-01                     1.7                       NaN
1980-01-02                     1.7                       NaN
1980-01-03                     1.7                       NaN
1980-01-04                     1.7                       NaN
1980-01-05                     1.7                       NaN

variable                                                      \
station    Presa Canelon Grande Picada de Varela Paso Roldan
date
1980-01-01                  NaN              NaN        2.95
1980-01-02                  NaN              NaN        2.95
1980-01-03                  NaN              NaN        2.95
1980-01-04                  NaN              NaN        2.94
1980-01-05                  NaN              NaN        2.94

variable
station    Paso de los Troncos Santa Lucia (Ruta 11) Las Brujas DINAGUA
date
1980-01-01                 0.3                   1.1               1.37
1980-01-02                 0.3                   1.1               0.68
1980-01-03                 0.3                   1.1               1.30
1980-01-04                 0.3                   1.1               1.62
1980-01-05                 0.3                   1.1               0.99

In [29]:
# Se seleccionan del dataset de dinagua el caudal y nivel de agua de la estación Florida (Puente Ruta 5)

idx = pd.IndexSlice
est = "Florida (Puente Ruta 5)"

data_dinagua_crudo = data_dinagua_crudo.loc[:, idx[["Caudal (Q) [m3/s]", "Nivel de agua (h) [m]"], [est]]]
data_dinagua_crudo.head()

variable         Caudal (Q) [m3/s]   Nivel de agua (h) [m]
station    Florida (Puente Ruta 5) Florida (Puente Ruta 5)
date
1980-01-01                     0.0                     1.7
1980-01-02                     0.0                     1.7
1980-01-03                     0.0                     1.7
1980-01-04                     0.0                     1.7
1980-01-05                     0.0                     1.7

In [30]:
import pandas as pd

# lectura del dataset crudo de INUMET
path_inumet_crudo = './0-Datasets/SL_MET_INUMET_1980_2025.xlsx'
raw = pd.read_excel(path_inumet_crudo, sheet_name=0, header=None)

# detectar filas "station" y "date" (en la primera columna)
col0 = raw.iloc[:, 0].astype(str).str.strip().str.lower()
station_row = col0[col0.eq("station")].index[0]
date_row    = col0[col0.eq("date")].index[0]

# la fila anterior a "station" suele contener el grupo/variable (celdas combinadas -> ffill)
var_row = station_row - 1

vars_ = raw.iloc[var_row, 1:].astype(str).str.strip()
vars_ = vars_.replace({"nan": None, "None": None}).ffill()

stations = raw.iloc[station_row, 1:].astype(str).str.strip()

# los datos empiezan después de la fila "date"
data_start = date_row + 1
dates = pd.to_datetime(raw.iloc[data_start:, 0], errors="coerce")
data  = raw.iloc[data_start:, 1:]

data_inumet_crudo = data.copy()
data_inumet_crudo.index = dates
data_inumet_crudo.index.name = "date"

data_inumet_crudo.columns = pd.MultiIndex.from_arrays(
    [vars_, stations],
    names=["variable", "station"]
)

# convertir a numérico
data_inumet_crudo = data_inumet_crudo.apply(pd.to_numeric, errors="coerce")

data_inumet_crudo.head()

variable   Precipitacion (P) [mm]                                             \
station              25 de Agosto Aeropuerto Melilla Barriga Negra Casupa_fr
date
1980-01-01                    0.0                0.0           NaN       NaN
1980-01-02                    0.0                0.0           NaN       NaN
1980-01-03                    0.0                0.0           NaN       NaN
1980-01-04                    0.0                0.0           NaN       NaN
1980-01-05                   13.0                9.0           NaN       NaN

variable                                                                  \
station    Cerro Colorado Chamanga Chamizo_fr Chamizo_sj Coronilla Cufre
date
1980-01-01            0.0      NaN        NaN        NaN       NaN   NaN
1980-01-02            0.0      NaN        NaN        NaN       NaN   NaN
1980-01-03            0.0      NaN        NaN        NaN       NaN   NaN
1980-01-04            0.0      NaN        NaN        NaN       NaN   NaN
1980-01-05           32.0      8.0        NaN        NaN       NaN   NaN

variable                                                           \
station    Fray Marcos La Cruz Marmaraja Mendoza Puntas del Sauce
date
1980-01-01         NaN     0.0       NaN     0.0              NaN
1980-01-02         NaN     0.0       NaN     0.0              NaN
1980-01-03         NaN     0.0       NaN     0.0              NaN
1980-01-04         NaN     0.0       NaN     0.0              NaN
1980-01-05         NaN     2.0       NaN     9.0             13.5

variable                                                                      \
station    Rincon del Pino San Gabriel Sarandi Grande Santa Lucia (LaCalera)
date
1980-01-01             NaN         0.0            0.0                    NaN
1980-01-02             NaN         0.0            0.0                    NaN
1980-01-03             NaN         0.0            0.0                    NaN
1980-01-04             NaN         0.0            0.0                    NaN
1980-01-05             NaN         9.0            4.0                   17.0

variable
station    Tala Villa 25 de Mayo Villa Cardal
date
1980-01-01  NaN              0.0          0.0
1980-01-02  NaN              0.0          0.0
1980-01-03  NaN              0.0          0.0
1980-01-04  NaN              0.0          0.0
1980-01-05  NaN              1.0          7.0

In [31]:
cols = ["Florida","Cerro Colorado","La Cruz","Mendoza","Reboledo","San Gabriel",
        "Sarandi Grande","Villa 25 de Mayo","Villa Cardal"]

data_inumet_crudo = data_inumet_crudo.loc[:, data_inumet_crudo.columns.get_level_values(1).isin(cols)].copy()

data_inumet_crudo.head()
# Se observa que en los datos crudos no están las estaciones de Florida y Reboledo
# No obstante, la creación de un dataset crudo "unificado" será sólo a los efectos de comparar el comportamiento de la variable fósforo y IET

variable   Precipitacion (P) [mm]                                             \
station            Cerro Colorado La Cruz Mendoza San Gabriel Sarandi Grande
date
1980-01-01                    0.0     0.0     0.0         0.0            0.0
1980-01-02                    0.0     0.0     0.0         0.0            0.0
1980-01-03                    0.0     0.0     0.0         0.0            0.0
1980-01-04                    0.0     0.0     0.0         0.0            0.0
1980-01-05                   32.0     2.0     9.0         9.0            4.0

variable
station    Villa 25 de Mayo Villa Cardal
date
1980-01-01              0.0          0.0
1980-01-02              0.0          0.0
1980-01-03              0.0          0.0
1980-01-04              0.0          0.0
1980-01-05              1.0          7.0

In [32]:
import pandas as pd

# lectura del dataset crudo de INIA
path_inia_crudo = './0-Datasets/SL_MET_INIA_1980_2025.xlsx'
raw = pd.read_excel(path_inia_crudo, sheet_name=0, header=None)

# detectar filas "station" y "date" (en la primera columna)
col0 = raw.iloc[:, 0].astype(str).str.strip().str.lower()
station_row = col0[col0.eq("station")].index[0]
date_row    = col0[col0.eq("date")].index[0]

# la fila anterior a "station" suele contener el grupo/variable (celdas combinadas -> ffill)
var_row = station_row - 1

vars_ = raw.iloc[var_row, 1:].astype(str).str.strip()
vars_ = vars_.replace({"nan": None, "None": None}).ffill()

stations = raw.iloc[station_row, 1:].astype(str).str.strip()

# los datos empiezan después de la fila "date"
data_start = date_row + 1
dates = pd.to_datetime(raw.iloc[data_start:, 0], errors="coerce")
data  = raw.iloc[data_start:, 1:]

data_inia_crudo = data.copy()
data_inia_crudo.index = dates
data_inia_crudo.index.name = "date"

data_inia_crudo.columns = pd.MultiIndex.from_arrays(
    [vars_, stations],
    names=["variable", "station"]
)

# convertir a numérico
data_inia_crudo = data_inia_crudo.apply(pd.to_numeric, errors="coerce")

data_inia_crudo.head()

variable,Evapotranspiracion Penman (ET) [mm],Heliofania (Hel) [hs],Humedad relativa media (HR) [%],Radiacion solar (RS) [cal/cm2/dia],Temperatura del aire media (TA) [ºC(24hs)],Temperatura del aire maxima (TA) [ºC],Temperatura del aire minima (TA) [ºC],Velocidad del viento (VV) [2m/km/24h]
station,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas
date,,,,,,,,
1980-01-01,5.5,10.5,66.0,597.5,18.5,23.0,14.0,190.1
1980-01-02,6.0,11.3,60.0,625.1,20.3,28.3,10.4,163.4
1980-01-03,6.6,11.1,68.0,617.8,21.7,28.1,15.9,284.1
1980-01-04,8.0,11.2,54.0,620.9,22.6,30.0,14.6,337.4
1980-01-05,5.9,3.5,58.0,353.0,23.7,28.6,17.2,292.3

In [33]:
# Se realiza el pasaje a valores promedios diarios mensuales (un valor por mes)

dinagua_mensual_crudo = data_dinagua_crudo.resample('ME').mean()

# Se ajusta el índice para asignar la fecha al último día de cada mes

dinagua_mensual_crudo.index = dinagua_mensual_crudo.index.to_period('M').to_timestamp('M')

dinagua_mensual_crudo.head()

variable         Caudal (Q) [m3/s]   Nivel de agua (h) [m]
station    Florida (Puente Ruta 5) Florida (Puente Ruta 5)
date
1980-01-31                     0.0                  1.6464
1980-02-29                     NaN                     NaN
1980-03-31                     NaN                     NaN
1980-04-30                     NaN                     NaN
1980-05-31                     NaN                     NaN

In [34]:
# Se realiza el pasaje a valores promedios diarios mensuales (un valor por mes)

inumet_mensual_crudo = data_inumet_crudo.resample('ME').mean()

# Se asegura que el índice quede exactamente como "último día"
inumet_mensual_crudo.index = inumet_mensual_crudo.index.to_period('M').to_timestamp('M')

inumet_mensual_crudo.head()

variable   Precipitacion (P) [mm]                                  \
station            Cerro Colorado   La Cruz   Mendoza San Gabriel
date
1980-01-31               1.774194  2.290323  1.351613    2.322581
1980-02-29               5.172414  8.758621  8.275862    8.586207
1980-03-31               5.451613  3.129032  5.641935    3.903226
1980-04-30               7.766667  3.866667  6.140000    5.866667
1980-05-31               5.854839  5.003226  6.516129    6.419355

variable
station    Sarandi Grande Villa 25 de Mayo Villa Cardal
date
1980-01-31       3.361290         1.032258     1.677419
1980-02-29       7.275862         4.796552     3.620690
1980-03-31       7.161290         6.516129     6.000000
1980-04-30       7.950000         4.243333     5.033333
1980-05-31      10.258065         5.403226     3.919355

In [35]:
# Se realiza el pasaje a valores promedios diarios mensuales (un valor por mes)

inia_mensual_crudo = data_inia_crudo.resample('ME').mean()

# Se ajusta el índice para asignar la fecha al último día de cada mes

inia_mensual_crudo.index = inia_mensual_crudo.index.to_period('M').to_timestamp('M')

inia_mensual_crudo.head()

variable,Evapotranspiracion Penman (ET) [mm],Heliofania (Hel) [hs],Humedad relativa media (HR) [%],Radiacion solar (RS) [cal/cm2/dia],Temperatura del aire media (TA) [ºC(24hs)],Temperatura del aire maxima (TA) [ºC],Temperatura del aire minima (TA) [ºC],Velocidad del viento (VV) [2m/km/24h]
station,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas,INIA Las Brujas
date,,,,,,,,
1980-01-31,6.700000,10.622581,64.548387,593.051613,23.338710,29.909677,16.751613,252.025806
1980-02-29,5.300000,9.617241,71.448276,522.500000,22.320690,28.306897,16.400000,212.551724
1980-03-31,3.838710,8.183871,80.451613,412.483871,22.858065,28.225806,17.912903,173.803226
1980-04-30,2.393333,5.146667,81.866667,258.876667,19.410000,23.856667,16.186667,246.483333
1980-05-31,1.180645,4.741935,86.193548,196.261290,15.558065,19.890323,11.612903,159.338710

In [36]:
# Se asegura que todos los sets tengan el mismo índice de fecha

data_dinacea_crudo.index = pd.to_datetime(data_dinacea_crudo.index)
dinagua_mensual_crudo.index = pd.to_datetime(dinagua_mensual_crudo.index)
inumet_mensual_crudo.index = pd.to_datetime(inumet_mensual_crudo.index)
inia_mensual_crudo.index = pd.to_datetime(inia_mensual_crudo.index)

# Se combinan los datasets

dataset_completo_crudo = pd.concat([data_dinacea_crudo, dinagua_mensual_crudo, inumet_mensual_crudo, inia_mensual_crudo], axis=1)

dataset_completo_crudo.head()

variable   Fósforo Total (PT) [μg/L]                                          \
station                      XSLH020 XSLH030 XSLH010 EPSE030 EPSE040 EPSE020
date
1980-01-31                       NaN     NaN     NaN     NaN     NaN     NaN
1980-02-29                       NaN     NaN     NaN     NaN     NaN     NaN
1980-03-31                       NaN     NaN     NaN     NaN     NaN     NaN
1980-04-30                       NaN     NaN     NaN     NaN     NaN     NaN
1980-05-31                       NaN     NaN     NaN     NaN     NaN     NaN

variable   Nitrógeno Total (NT) [mg/L]                                  \
station                        XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
1980-01-31                         NaN     NaN     NaN     NaN     NaN
1980-02-29                         NaN     NaN     NaN     NaN     NaN
1980-03-31                         NaN     NaN     NaN     NaN     NaN
1980-04-30                         NaN     NaN     NaN     NaN     NaN
1980-05-31                         NaN     NaN     NaN     NaN     NaN

variable           Ion Nitrato (NO3-) [mg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
1980-01-31     NaN                       NaN     NaN     NaN     NaN     NaN
1980-02-29     NaN                       NaN     NaN     NaN     NaN     NaN
1980-03-31     NaN                       NaN     NaN     NaN     NaN     NaN
1980-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
1980-05-31     NaN                       NaN     NaN     NaN     NaN     NaN

variable           Ion Nitrito (NO2-) [mg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
1980-01-31     NaN                       NaN     NaN     NaN     NaN     NaN
1980-02-29     NaN                       NaN     NaN     NaN     NaN     NaN
1980-03-31     NaN                       NaN     NaN     NaN     NaN     NaN
1980-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
1980-05-31     NaN                       NaN     NaN     NaN     NaN     NaN

variable           Ion Amonio (NH4+) [mg/L]                                  \
station    EPSE020                  XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
1980-01-31     NaN                      NaN     NaN     NaN     NaN     NaN
1980-02-29     NaN                      NaN     NaN     NaN     NaN     NaN
1980-03-31     NaN                      NaN     NaN     NaN     NaN     NaN
1980-04-30     NaN                      NaN     NaN     NaN     NaN     NaN
1980-05-31     NaN                      NaN     NaN     NaN     NaN     NaN

variable           Ion Fosfato (PO4-) [µg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
1980-01-31     NaN                       NaN     NaN     NaN     NaN     NaN
1980-02-29     NaN                       NaN     NaN     NaN     NaN     NaN
1980-03-31     NaN                       NaN     NaN     NaN     NaN     NaN
1980-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
1980-05-31     NaN                       NaN     NaN     NaN     NaN     NaN

variable           Glifosato [µg/L]                                          \
station    EPSE020          XSLH020 XSLH030 XSLH010 EPSE030 EPSE040 EPSE020
date
1980-01-31     NaN              NaN     NaN     NaN     NaN     NaN     NaN
1980-02-29     NaN              NaN     NaN     NaN     NaN     NaN     NaN
1980-03-31     NaN              NaN     NaN     NaN     NaN     NaN     NaN
1980-04-30     NaN              NaN     NaN     NaN     NaN     NaN     NaN
1980-05-31     NaN              NaN     NaN     NaN     NaN     NaN     NaN

variable   Solidos totales (ST) [mg/L]                                  \
station                        XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
1980-01-31                         NaN     NaN     NaN     NaN     NaN
1980-02-29                         NaN     NaN     NaN     NaN     NaN
1980-03-31                         NaN     NaN     NaN     NaN     NaN
1980-04-30                         NaN     NaN     NaN     NaN     NaN
1980-05-31                         NaN     NaN     NaN     NaN     NaN

variable           Solidos suspendidos totales (SST) [mg/L]                  \
station    EPSE020                                  XSLH020 XSLH030 XSLH010
date
1980-01-31     NaN                                      NaN     NaN     NaN
1980-02-29     NaN                                      NaN     NaN     NaN
1980-03-31     NaN                                      NaN     NaN     NaN
1980-04-30     NaN                                      NaN     NaN     NaN
1980-05-31     NaN                                      NaN     NaN     NaN

variable                           Turbidez [NTU]                          \
station    EPSE030 EPSE040 EPSE020        XSLH020 XSLH030 XSLH010 EPSE030
date
1980-01-31     NaN     NaN     NaN            NaN     NaN     NaN     NaN
1980-02-29     NaN     NaN     NaN            NaN     NaN     NaN     NaN
1980-03-31     NaN     NaN     NaN            NaN     NaN     NaN     NaN
1980-04-30     NaN     NaN     NaN            NaN     NaN     NaN     NaN
1980-05-31     NaN     NaN     NaN            NaN     NaN     NaN     NaN

variable                   Temperatura del agua (T) [ºC]                  \
station    EPSE040 EPSE020                       XSLH020 XSLH030 XSLH010
date
1980-01-31     NaN     NaN                           NaN     NaN     NaN
1980-02-29     NaN     NaN                           NaN     NaN     NaN
1980-03-31     NaN     NaN                           NaN     NaN     NaN
1980-04-30     NaN     NaN                           NaN     NaN     NaN
1980-05-31     NaN     NaN                           NaN     NaN     NaN

variable                           Oxigeno Disuelto (OD) [mg/L]          \
station    EPSE030 EPSE040 EPSE020                      XSLH020 XSLH030
date
1980-01-31     NaN     NaN     NaN                          NaN     NaN
1980-02-29     NaN     NaN     NaN                          NaN     NaN
1980-03-31     NaN     NaN     NaN                          NaN     NaN
1980-04-30     NaN     NaN     NaN                          NaN     NaN
1980-05-31     NaN     NaN     NaN                          NaN     NaN

variable                                    \
station    XSLH010 EPSE030 EPSE040 EPSE020
date
1980-01-31     NaN     NaN     NaN     NaN
1980-02-29     NaN     NaN     NaN     NaN
1980-03-31     NaN     NaN     NaN     NaN
1980-04-30     NaN     NaN     NaN     NaN
1980-05-31     NaN     NaN     NaN     NaN

variable   Demanda Bioquímica de Oxigeno (DBO) [mg/L]                          \
station                                       XSLH020 XSLH030 XSLH010 EPSE030
date
1980-01-31                                        NaN     NaN     NaN     NaN
1980-02-29                                        NaN     NaN     NaN     NaN
1980-03-31                                        NaN     NaN     NaN     NaN
1980-04-30                                        NaN     NaN     NaN     NaN
1980-05-31                                        NaN     NaN     NaN     NaN

variable                   Clorofila-a (Chl-a) [μg/L]                          \
station    EPSE040 EPSE020                    XSLH020 XSLH030 XSLH010 EPSE030
date
1980-01-31     NaN     NaN                        NaN     NaN     NaN     NaN
1980-02-29     NaN     NaN                        NaN     NaN     NaN     NaN
1980-03-31     NaN     NaN                        NaN     NaN     NaN     NaN
1980-04-30     NaN     NaN                        NaN     NaN     NaN     NaN
1980-05-31     NaN     NaN                        NaN     NaN     NaN     NaN

variable                   Potencial de Hidrogeno (pH) [NA]                  \
station    EPSE040 EPSE020                          XSLH020 XSLH030 XSLH010
date
1980-01-31     NaN     NaN                              NaN     NaN     NaN
1980-02-29     NaN     NaN                              NaN     NaN     NaN
1980-03-31     NaN     NaN                              NaN     NaN     NaN
1980-04-30     NaN     NaN                              NaN     NaN     NaN
1980-05-31     NaN     NaN                              NaN     NaN     NaN

variable                           Conductividad [μS/cm]                  \
station    EPSE030 EPSE040 EPSE020               XSLH020 XSLH030 XSLH010
date
1980-01-31     NaN     NaN     NaN                   NaN     NaN     NaN
1980-02-29     NaN     NaN     NaN                   NaN     NaN     NaN
1980-03-31     NaN     NaN     NaN                   NaN     NaN     NaN
1980-04-30     NaN     NaN     NaN                   NaN     NaN     NaN
1980-05-31     NaN     NaN     NaN                   NaN     NaN     NaN

variable                                 Caudal (Q) [m3/s]  \
station    EPSE030 EPSE040 EPSE020 Florida (Puente Ruta 5)
date
1980-01-31     NaN     NaN     NaN                     0.0
1980-02-29     NaN     NaN     NaN                     NaN
1980-03-31     NaN     NaN     NaN                     NaN
1980-04-30     NaN     NaN     NaN                     NaN
1980-05-31     NaN     NaN     NaN                     NaN

variable     Nivel de agua (h) [m] Precipitacion (P) [mm]                      \
station    Florida (Puente Ruta 5)         Cerro Colorado   La Cruz   Mendoza
date
1980-01-31                  1.6464               1.774194  2.290323  1.351613
1980-02-29                     NaN               5.172414  8.758621  8.275862
1980-03-31                     NaN               5.451613  3.129032  5.641935
1980-04-30                     NaN               7.766667  3.866667  6.140000
1980-05-31                     NaN               5.854839  5.003226  6.516129

variable                                                             \
station    San Gabriel Sarandi Grande Villa 25 de Mayo Villa Cardal
date
1980-01-31    2.322581       3.361290         1.032258     1.677419
1980-02-29    8.586207       7.275862         4.796552     3.620690
1980-03-31    3.903226       7.161290         6.516129     6.000000
1980-04-30    5.866667       7.950000         4.243333     5.033333
1980-05-31    6.419355      10.258065         5.403226     3.919355

variable   Evapotranspiracion Penman (ET) [mm] Heliofania (Hel) [hs]  \
station                        INIA Las Brujas       INIA Las Brujas
date
1980-01-31                            6.700000             10.622581
1980-02-29                            5.300000              9.617241
1980-03-31                            3.838710              8.183871
1980-04-30                            2.393333              5.146667
1980-05-31                            1.180645              4.741935

variable   Humedad relativa media (HR) [%] Radiacion solar (RS) [cal/cm2/dia]  \
station                    INIA Las Brujas                    INIA Las Brujas
date
1980-01-31                       64.548387                         593.051613
1980-02-29                       71.448276                         522.500000
1980-03-31                       80.451613                         412.483871
1980-04-30                       81.866667                         258.876667
1980-05-31                       86.193548                         196.261290

variable   Temperatura del aire media (TA) [ºC(24hs)]  \
station                               INIA Las Brujas
date
1980-01-31                                  23.338710
1980-02-29                                  22.320690
1980-03-31                                  22.858065
1980-04-30                                  19.410000
1980-05-31                                  15.558065

variable   Temperatura del aire maxima (TA) [ºC]  \
station                          INIA Las Brujas
date
1980-01-31                             29.909677
1980-02-29                             28.306897
1980-03-31                             28.225806
1980-04-30                             23.856667
1980-05-31                             19.890323

variable   Temperatura del aire minima (TA) [ºC]  \
station                          INIA Las Brujas
date
1980-01-31                             16.751613
1980-02-29                             16.400000
1980-03-31                             17.912903
1980-04-30                             16.186667
1980-05-31                             11.612903

variable   Velocidad del viento (VV) [2m/km/24h]
station                          INIA Las Brujas
date
1980-01-31                            252.025806
1980-02-29                            212.551724
1980-03-31                            173.803226
1980-04-30                            246.483333
1980-05-31                            159.338710

In [37]:
dataset_completo_crudo = dataset_completo_crudo.loc["2014-01-01":"2022-12-31"].copy()

dataset_completo_crudo.head()

variable   Fósforo Total (PT) [μg/L]                                          \
station                      XSLH020 XSLH030 XSLH010 EPSE030 EPSE040 EPSE020
date
2014-01-31                     351.0   475.0   181.0   456.0   474.0   505.0
2014-02-28                       NaN     NaN     NaN     NaN     NaN     NaN
2014-03-31                     420.0   210.0    78.0   400.0   390.0   390.0
2014-04-30                       NaN     NaN     NaN     NaN     NaN     NaN
2014-05-31                     198.0   202.0   117.0   389.0   361.0   340.0

variable   Nitrógeno Total (NT) [mg/L]                                  \
station                        XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2014-01-31                        1.18    2.37    1.07    1.44    1.51
2014-02-28                         NaN     NaN     NaN     NaN     NaN
2014-03-31                        1.08    0.99    0.96    1.28    1.26
2014-04-30                         NaN     NaN     NaN     NaN     NaN
2014-05-31                        1.29    1.02    1.42    1.29    1.25

variable           Ion Nitrato (NO3-) [mg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2014-01-31    1.83                      0.27    0.87    0.18    0.72    0.72
2014-02-28     NaN                       NaN     NaN     NaN     NaN     NaN
2014-03-31    1.34                      0.16    0.34    0.10    0.51    0.54
2014-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
2014-05-31    1.28                      0.55    0.60    0.88    0.60    0.52

variable           Ion Nitrito (NO2-) [mg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2014-01-31    0.92                    0.0450  0.2100  0.0200   0.016   0.020
2014-02-28     NaN                       NaN     NaN     NaN     NaN     NaN
2014-03-31    0.54                    0.0029  0.0065  0.0029     NaN   0.014
2014-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
2014-05-31    0.61                    0.0160  0.0160  0.0160   0.016   0.016

variable           Ion Amonio (NH4+) [mg/L]                                  \
station    EPSE020                  XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2014-01-31  0.0160                    0.070   0.160    0.04    0.05   0.070
2014-02-28     NaN                      NaN     NaN     NaN     NaN     NaN
2014-03-31  0.0012                    0.041   0.043    0.02    0.03   0.014
2014-04-30     NaN                      NaN     NaN     NaN     NaN     NaN
2014-05-31  0.0160                    0.060   0.080    0.27    0.01   0.010

variable           Ion Fosfato (PO4-) [µg/L]                                  \
station    EPSE020                   XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2014-01-31   0.040                       NaN     NaN     NaN     NaN     NaN
2014-02-28     NaN                       NaN     NaN     NaN     NaN     NaN
2014-03-31   0.013                       NaN     NaN     NaN     NaN     NaN
2014-04-30     NaN                       NaN     NaN     NaN     NaN     NaN
2014-05-31   0.050                       NaN     NaN     NaN     NaN     NaN

variable           Glifosato [µg/L]                                          \
station    EPSE020          XSLH020 XSLH030 XSLH010 EPSE030 EPSE040 EPSE020
date
2014-01-31     NaN              NaN     NaN     NaN     NaN     NaN     0.3
2014-02-28     NaN              NaN     NaN     NaN     NaN     NaN     NaN
2014-03-31     NaN              NaN     NaN     NaN     NaN     NaN     0.2
2014-04-30     NaN              NaN     NaN     NaN     NaN     NaN     NaN
2014-05-31     NaN              NaN     NaN     NaN     NaN     NaN     1.0

variable   Solidos totales (ST) [mg/L]                                  \
station                        XSLH020 XSLH030 XSLH010 EPSE030 EPSE040
date
2014-01-31                         NaN     NaN     NaN     NaN     NaN
2014-02-28                         NaN     NaN     NaN     NaN     NaN
2014-03-31                         NaN     NaN     NaN     NaN     NaN
2014-04-30                         NaN     NaN     NaN     NaN     NaN
2014-05-31                         NaN     NaN     NaN     NaN     NaN

variable           Solidos suspendidos totales (SST) [mg/L]                  \
station    EPSE020                                  XSLH020 XSLH030 XSLH010
date
2014-01-31     NaN                                      NaN     NaN     NaN
2014-02-28     NaN                                      NaN     NaN     NaN
2014-03-31     NaN                                      NaN     NaN     NaN
2014-04-30     NaN                                      NaN     NaN     NaN
2014-05-31     NaN                                      NaN     NaN     NaN

variable                           Turbidez [NTU]                          \
station    EPSE030 EPSE040 EPSE020        XSLH020 XSLH030 XSLH010 EPSE030
date
2014-01-31     NaN     NaN     NaN            9.0     5.7    12.0     8.3
2014-02-28     NaN     NaN     NaN            NaN     NaN     NaN     NaN
2014-03-31     NaN     NaN     NaN           15.0    13.0    18.0    19.0
2014-04-30     NaN     NaN     NaN            NaN     NaN     NaN     NaN
2014-05-31     NaN     NaN     NaN           18.0    15.0    18.0    25.0

variable                   Temperatura del agua (T) [ºC]                  \
station    EPSE040 EPSE020                       XSLH020 XSLH030 XSLH010
date
2014-01-31     8.8    11.0                          26.9    26.8    25.5
2014-02-28     NaN     NaN                           NaN     NaN     NaN
2014-03-31    15.0    15.0                          18.8    19.7    18.7
2014-04-30     NaN     NaN                           NaN     NaN     NaN
2014-05-31    26.0    25.0                          17.0    17.4    17.2

variable                           Oxigeno Disuelto (OD) [mg/L]          \
station    EPSE030 EPSE040 EPSE020                      XSLH020 XSLH030
date
2014-01-31    27.2    27.4    26.6                         5.48    3.60
2014-02-28     NaN     NaN     NaN                          NaN     NaN
2014-03-31    21.9    22.1    22.4                         7.88    7.48
2014-04-30     NaN     NaN     NaN                          NaN     NaN
2014-05-31    18.0    18.0    17.9                         8.35    8.06

variable                                    \
station    XSLH010 EPSE030 EPSE040 EPSE020
date
2014-01-31    5.65    6.72    6.48    5.94
2014-02-28     NaN     NaN     NaN     NaN
2014-03-31    7.18    7.03    7.04    6.51
2014-04-30     NaN     NaN     NaN     NaN
2014-05-31     NaN    7.10    6.71    7.14

variable   Demanda Bioquímica de Oxigeno (DBO) [mg/L]                          \
station                                       XSLH020 XSLH030 XSLH010 EPSE030
date
2014-01-31                                        0.8     1.2     1.1     NaN
2014-02-28                                        NaN     NaN     NaN     NaN
2014-03-31                                        2.7     1.7     1.7     NaN
2014-04-30                                        NaN     NaN     NaN     NaN
2014-05-31                                        2.6     3.4     6.2     NaN

variable                   Clorofila-a (Chl-a) [μg/L]                          \
station    EPSE040 EPSE020                    XSLH020 XSLH030 XSLH010 EPSE030
date
2014-01-31     NaN     NaN                        NaN    4.40     NaN     0.7
2014-02-28     NaN     NaN                        NaN     NaN     NaN     NaN
2014-03-31     NaN     NaN                        NaN    0.40     NaN     0.4
2014-04-30     NaN     NaN                        NaN     NaN     NaN     NaN
2014-05-31     NaN     NaN                        NaN    0.05     NaN     0.4

variable                   Potencial de Hidrogeno (pH) [NA]                  \
station    EPSE040 EPSE020                          XSLH020 XSLH030 XSLH010
date
2014-01-31     0.5     0.3                             7.58    7.49    7.50
2014-02-28     NaN     NaN                              NaN     NaN     NaN
2014-03-31     0.1     0.1                             7.63    7.83    7.65
2014-04-30     NaN     NaN                              NaN     NaN     NaN
2014-05-31     0.4     0.7                             7.49    7.34    7.41

variable                           Conductividad [μS/cm]                  \
station    EPSE030 EPSE040 EPSE020               XSLH020 XSLH030 XSLH010
date
2014-01-31    7.93    7.69    7.63                 239.1   301.2   234.5
2014-02-28     NaN     NaN     NaN                   NaN     NaN     NaN
2014-03-31    7.57    7.61    7.70                 191.0   204.6   146.4
2014-04-30     NaN     NaN     NaN                   NaN     NaN     NaN
2014-05-31    7.35    7.30    7.22                 173.6   187.3   143.7

variable                                 Caudal (Q) [m3/s]  \
station    EPSE030 EPSE040 EPSE020 Florida (Puente Ruta 5)
date
2014-01-31   239.8   240.9   240.6               12.228097
2014-02-28     NaN     NaN     NaN              113.725571
2014-03-31   182.9   154.5   142.8                7.386935
2014-04-30     NaN     NaN     NaN               60.504200
2014-05-31   104.6    95.5   132.3               14.999000

variable     Nivel de agua (h) [m] Precipitacion (P) [mm]                      \
station    Florida (Puente Ruta 5)         Cerro Colorado   La Cruz   Mendoza
date
2014-01-31                2.535161               9.677419  7.000000  8.225806
2014-02-28                3.562500              12.500000  8.042857  8.814815
2014-03-31                2.451290               2.645161  3.161290  2.965517
2014-04-30                2.677333               4.366667  4.900000  3.827586
2014-05-31                2.522903               3.451613  3.441935  2.666667

variable                                                             \
station    San Gabriel Sarandi Grande Villa 25 de Mayo Villa Cardal
date
2014-01-31    7.935484       7.193548         8.366667    11.433333
2014-02-28    7.285714       9.892857         8.000000     9.117857
2014-03-31    3.133333       3.806452         3.290323     3.400000
2014-04-30    4.433333       4.266667         5.500000     4.655172
2014-05-31    3.310345       3.322581         3.129032     3.666667

variable   Evapotranspiracion Penman (ET) [mm] Heliofania (Hel) [hs]  \
station                        INIA Las Brujas       INIA Las Brujas
date
2014-01-31                            5.506452              8.529032
2014-02-28                            4.060714              6.560714
2014-03-31                            3.638710              7.867742
2014-04-30                            2.203333              6.710000
2014-05-31                            1.138710              4.200000

variable   Humedad relativa media (HR) [%] Radiacion solar (RS) [cal/cm2/dia]  \
station                    INIA Las Brujas                    INIA Las Brujas
date
2014-01-31                       67.645161                         521.180645
2014-02-28                       76.500000                         421.378571
2014-03-31                       71.193548                         405.835484
2014-04-30                       76.133333                         298.750000
2014-05-31                       81.677419                         185.232258

variable   Temperatura del aire media (TA) [ºC(24hs)]  \
station                               INIA Las Brujas
date
2014-01-31                                  23.329032
2014-02-28                                  21.425000
2014-03-31                                  19.058065
2014-04-30                                  16.613333
2014-05-31                                  12.948387

variable   Temperatura del aire maxima (TA) [ºC]  \
station                          INIA Las Brujas
date
2014-01-31                             28.854839
2014-02-28                             26.421429
2014-03-31                             24.693548
2014-04-30                             22.150000
2014-05-31                             17.748387

variable   Temperatura del aire minima (TA) [ºC]  \
station                          INIA Las Brujas
date
2014-01-31                             17.783871
2014-02-28                             17.607143
2014-03-31                             13.783871
2014-04-30                             11.930000
2014-05-31                              8.906452

variable   Velocidad del viento (VV) [2m/km/24h]
station                          INIA Las Brujas
date
2014-01-31                            162.916129
2014-02-28                            140.932143
2014-03-31                            169.254839
2014-04-30                            148.876667
2014-05-31                            127.487097

In [38]:
dataset_completo_crudo.columns = [' '.join(col).strip() for col in dataset_completo_crudo.columns.values]
dataset_completo_crudo.head()

,Fósforo Total (PT) [μg/L] XSLH020,Fósforo Total (PT) [μg/L] XSLH030,Fósforo Total (PT) [μg/L] XSLH010,Fósforo Total (PT) [μg/L] EPSE030,Fósforo Total (PT) [μg/L] EPSE040,Fósforo Total (PT) [μg/L] EPSE020,Nitrógeno Total (NT) [mg/L] XSLH020,Nitrógeno Total (NT) [mg/L] XSLH030,Nitrógeno Total (NT) [mg/L] XSLH010,Nitrógeno Total (NT) [mg/L] EPSE030,Nitrógeno Total (NT) [mg/L] EPSE040,Nitrógeno Total (NT) [mg/L] EPSE020,Ion Nitrato (NO3-) [mg/L] XSLH020,Ion Nitrato (NO3-) [mg/L] XSLH030,Ion Nitrato (NO3-) [mg/L] XSLH010,Ion Nitrato (NO3-) [mg/L] EPSE030,Ion Nitrato (NO3-) [mg/L] EPSE040,Ion Nitrato (NO3-) [mg/L] EPSE020,Ion Nitrito (NO2-) [mg/L] XSLH020,Ion Nitrito (NO2-) [mg/L] XSLH030,Ion Nitrito (NO2-) [mg/L] XSLH010,Ion Nitrito (NO2-) [mg/L] EPSE030,Ion Nitrito (NO2-) [mg/L] EPSE040,Ion Nitrito (NO2-) [mg/L] EPSE020,Ion Amonio (NH4+) [mg/L] XSLH020,Ion Amonio (NH4+) [mg/L] XSLH030,Ion Amonio (NH4+) [mg/L] XSLH010,Ion Amonio (NH4+) [mg/L] EPSE030,Ion Amonio (NH4+) [mg/L] EPSE040,Ion Amonio (NH4+) [mg/L] EPSE020,Ion Fosfato (PO4-) [µg/L] XSLH020,Ion Fosfato (PO4-) [µg/L] XSLH030,Ion Fosfato (PO4-) [µg/L] XSLH010,Ion Fosfato (PO4-) [µg/L] EPSE030,Ion Fosfato (PO4-) [µg/L] EPSE040,Ion Fosfato (PO4-) [µg/L] EPSE020,Glifosato [µg/L] XSLH020,Glifosato [µg/L] XSLH030,Glifosato [µg/L] XSLH010,Glifosato [µg/L] EPSE030,Glifosato [µg/L] EPSE040,Glifosato [µg/L] EPSE020,Solidos totales (ST) [mg/L] XSLH020,Solidos totales (ST) [mg/L] XSLH030,Solidos totales (ST) [mg/L] XSLH010,Solidos totales (ST) [mg/L] EPSE030,Solidos totales (ST) [mg/L] EPSE040,Solidos totales (ST) [mg/L] EPSE020,Solidos suspendidos totales (SST) [mg/L] XSLH020,Solidos suspendidos totales (SST) [mg/L] XSLH030,Solidos suspendidos totales (SST) [mg/L] XSLH010,Solidos suspendidos totales (SST) [mg/L] EPSE030,Solidos suspendidos totales (SST) [mg/L] EPSE040,Solidos suspendidos totales (SST) [mg/L] EPSE020,Turbidez [NTU] XSLH020,Turbidez [NTU] XSLH030,Turbidez [NTU] XSLH010,Turbidez [NTU] EPSE030,Turbidez [NTU] EPSE040,Turbidez [NTU] EPSE020,Temperatura del agua (T) [ºC] XSLH020,Temperatura del agua (T) [ºC] XSLH030,Temperatura del agua (T) [ºC] XSLH010,Temperatura del agua (T) [ºC] EPSE030,Temperatura del agua (T) [ºC] EPSE040,Temperatura del agua (T) [ºC] EPSE020,Oxigeno Disuelto (OD) [mg/L] XSLH020,Oxigeno Disuelto (OD) [mg/L] XSLH030,Oxigeno Disuelto (OD) [mg/L] XSLH010,Oxigeno Disuelto (OD) [mg/L] EPSE030,Oxigeno Disuelto (OD) [mg/L] EPSE040,Oxigeno Disuelto (OD) [mg/L] EPSE020,Demanda Bioquímica de Oxigeno (DBO) [mg/L] XSLH020,Demanda Bioquímica de Oxigeno (DBO) [mg/L] XSLH030,Demanda Bioquímica de Oxigeno (DBO) [mg/L] XSLH010,Demanda Bioquímica de Oxigeno (DBO) [mg/L] EPSE030,Demanda Bioquímica de Oxigeno (DBO) [mg/L] EPSE040,Demanda Bioquímica de Oxigeno (DBO) [mg/L] EPSE020,Clorofila-a (Chl-a) [μg/L] XSLH020,Clorofila-a (Chl-a) [μg/L] XSLH030,Clorofila-a (Chl-a) [μg/L] XSLH010,Clorofila-a (Chl-a) [μg/L] EPSE030,Clorofila-a (Chl-a) [μg/L] EPSE040,Clorofila-a (Chl-a) [μg/L] EPSE020,Potencial de Hidrogeno (pH) [NA] XSLH020,Potencial de Hidrogeno (pH) [NA] XSLH030,Potencial de Hidrogeno (pH) [NA] XSLH010,Potencial de Hidrogeno (pH) [NA] EPSE030,Potencial de Hidrogeno (pH) [NA] EPSE040,Potencial de Hidrogeno (pH) [NA] EPSE020,Conductividad [μS/cm] XSLH020,Conductividad [μS/cm] XSLH030,Conductividad [μS/cm] XSLH010,Conductividad [μS/cm] EPSE030,Conductividad [μS/cm] EPSE040,Conductividad [μS/cm] EPSE020,Caudal (Q) [m3/s] Florida (Puente Ruta 5),Nivel de agua (h) [m] Florida (Puente Ruta 5),Precipitacion (P) [mm] Cerro Colorado,Precipitacion (P) [mm] La Cruz,Precipitacion (P) [mm] Mendoza,Precipitacion (P) [mm] San Gabriel,Precipitacion (P) [mm] Sarandi Grande,Precipitacion (P) [mm] Villa 25 de Mayo,Precipitacion (P) [mm] Villa Cardal,Evapotranspiracion Penman (ET) [mm] INIA Las Brujas,Heliofania (Hel) [hs] INIA Las Brujas,Humedad relativa media (HR) [%] INIA Las Brujas,Radiacion solar (RS) [cal/cm2/dia] INIA Las Brujas,Temperatura del aire media (TA) [ºC(24hs)] INIA Las Brujas,Temperatura del aire maxima (TA) [ºC] INIA Las Brujas,Temperatura del aire minima (TA) [ºC] INIA Las Brujas,Velocidad del viento (VV) [2m/km/24h] INIA Las Brujas
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-31,351.0,475.0,181.0,456.0,474.0,505.0,1.18,2.37,1.07,1.44,1.51,1.83,0.270,0.870,0.180,0.72,0.72,0.92,0.0450,0.2100,0.0200,0.0160,0.0200,0.0160,0.070,0.160,0.040,0.050,0.070,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.00,5.70,12.00,8.3,8.80,11.00,26.9,26.8,25.5,27.2,27.4,26.6,5.48,3.60,5.65,6.72,6.48,5.94,0.80,1.20,1.10,NaN,NaN,NaN,NaN,4.40,NaN,0.7,0.5,0.30,7.58,7.49,7.50,7.93,7.69,7.63,239.1,301.2,234.5,239.8,240.9,240.6,12.228097,2.535161,9.677419,7.000000,8.225806,7.935484,7.193548,8.366667,11.433333,5.506452,8.529032,67.645161,521.180645,23.329032,28.854839,17.783871,162.916129
2014-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.725571,3.562500,12.500000,8.042857,8.814815,7.285714,9.892857,8.000000,9.117857,4.060714,6.560714,76.500000,421.378571,21.425000,26.421429,17.607143,140.932143
2014-03-31,420.0,210.0,78.0,400.0,390.0,390.0,1.08,0.99,0.96,1.28,1.26,1.34,0.160,0.340,0.100,0.51,0.54,0.54,0.0029,0.0065,0.0029,NaN,0.0140,0.0012,0.041,0.043,0.020,0.030,0.014,0.013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.00,13.00,18.00,19.0,15.00,15.00,18.8,19.7,18.7,21.9,22.1,22.4,7.88,7.48,7.18,7.03,7.04,6.51,2.70,1.70,1.70,NaN,NaN,NaN,NaN,0.40,NaN,0.4,0.1,0.10,7.63,7.83,7.65,7.57,7.61,7.70,191.0,204.6,146.4,182.9,154.5,142.8,7.386935,2.451290,2.645161,3.161290,2.965517,3.133333,3.806452,3.290323,3.400000,3.638710,7.867742,71.193548,405.835484,19.058065,24.693548,13.783871,169.254839
2014-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.504200,2.677333,4.366667,4.900000,3.827586,4.433333,4.266667,5.500000,4.655172,2.203333,6.710000,76.133333,298.750000,16.613333,22.150000,11.930000,148.876667
2014-05-31,198.0,202.0,117.0,389.0,361.0,340.0,1.29,1.02,1.42,1.29,1.25,1.28,0.550,0.600,0.880,0.60,0.52,0.61,0.0160,0.0160,0.0160,0.0160,0.0160,0.0160,0.060,0.080,0.270,0.010,0.010,0.050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.00,15.00,18.00,25.0,26.00,25.00,17.0,17.4,17.2,18.0,18.0,17.9,8.35,8.06,NaN,7.10,6.71,7.14,2.60,3.40,6.20,NaN,NaN,NaN,NaN,0.05,NaN,0.4,0.4,0.70,7.49,7.34,7.41,7.35,7.30,7.22,173.6,187.3,143.7,104.6,95.5,132.3,14.999000,2.522903,3.451613,3.441935,2.666667,3.310345,3.322581,3.129032,3.666667,1.138710,4.200000,81.677419,185.232258,12.948387,17.748387,8.906452,127.487097
2014-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.664900,2.774000,2.233333,2.593333,1.586207,2.000000,3.100000,2.166667,1.733333,0.896667,5.763333,78.800000,190.750000,10.190000,15.840000,4.896667,149.986667
2014-07-31,142.0,151.0,28.0,205.0,197.0,221.0,1.50,1.76,0.99,1.58,1.41,1.39,0.500,0.690,0.260,0.55,0.45,0.51,0.0200,0.0200,0.0200,0.0200,0.0200,0.0200,0.010,0.010,0.040,0.010,0.010,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.00,45.00,40.00,50.0,40.00,40.00,10.6,10.7,9.4,12.5,12.5,12.8,10.35,10.32,11.40,8.69,8.54,8.26,2.60,3.40,2.20,NaN,NaN,NaN,NaN,0.30,NaN,0.4,0.6,0.60,7.32,8.01,7.51,7.44,6.98,7.15,78.3,81.0,78.9,62.0,65.6,72.3,129.676774,3.696129,5.645161,4.225806,3.689655,5.645161,4.677419,4.354839,4.806452,1.090323,5.516129,78.709677,198.241935,11.129032,15.980645,6.448387,170.651613
2014-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.627484,2.842903,0.806452,1.125806,0.600000,0.806452,0.774194,1.161290,0.874194,1.919355,6.803226,73.193548,275.393548,12.503226,18.735484,7.041935,187.583871
2014-09-30,224.0,252.0,164.0,329.0,282.0,300.0,1.04,1.37,1.01,1.07,0.99,1.17,0.310,0.370,0.140,0.20,0.17,0.17,0.0160,0.0920,0.0160,0.0160,0.0160,0.0160,0.010,0.010,0.010,0.010,0.010,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.00,21.00,20.00,29.0,27.00,27.00,16.6,17.6,17.2,16.9,18.6,18.1,8.62,8.39,9.48,7.34,7.51,7.36,NaN,NaN,0.50,NaN,NaN,NaN,NaN,0.40,NaN,0.4,1.2,0.40,7.77,7.98,7.47,7.53,7.13,7.16,143.1,155.5,139.1,57.8,61.2,66.8,184.529333,3.428000,11.233333,12.033333,8.551724,10.000000,8.400000,8.233333,8.073333,2.770000,7.016667,73.833333,354.033333,14.453333,20.080000,9.366667,193.606667
2014-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.221194,2.832258,3.612903,4.929032,4.733333,3.548387,4.129032,4.967742,6.064516,4.122581,7.858065,71.032258,444.680645,18.170968,23.616129,12.809677,192.151613
2014-11-30,64.8,NaN,26.3,195.0,292.0,201.0,1.23,NaN,1.13,1.44,1.29,1.40,0.020,NaN,0.020,0.02,0.02,0.02,0.0160,NaN,0.0160,0.0160,0.0160,0.0160,0.010,NaN,0.010,0.010,0.010,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.00,NaN,16.00,19.0,15.00,13.00,21.9,NaN,22.0,24.2,23.0,24.0,8.12,NaN,7.51,7.04,7.28,7.64,0.25,NaN,1.20,NaN,NaN,NaN,NaN,NaN,NaN,18.0,4.9,12.00,7.75,NaN,7.75,7.41,7.55,7.60,162.2,NaN,169.5,108.0,102.3,105.9,56.546200,3.020333,7.800000,7.133333,7.827586,8.866667,6.100000,8.766667,8.336667,4.863333,8.940000,67.833333,524.883333,18.770000,24.630000,12.680000,178.833333
2014-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.420355,2.870645,3.967742,2.054839,0.827586,1.000000,3.900000,2.258065,2.967742,5.600000,9.725806,66.580645,570.174194,21.396774,27.241935,15.767742,156.977419
2015-01-31,324.0,NaN,130.0,441.0,454.0,465.0,0.93,NaN,0.43,1.01,1.04,1.05,0.630,NaN,0.260,0.70,0.70,0.37,0.0160,NaN,0.0160,0.0160,0.0160,0.0160,0.010,NaN,0.010,0.010,0.010,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.00,NaN,33.00,16.0,13.00,14.00,22.3,NaN,22.4,26.0,25.9,25.4,6.71,NaN,7.17,6.10,6.37,6.22,1.30,NaN,1.60,NaN,NaN,NaN,NaN,NaN,NaN,0.7,0.3,0.60,7.94,NaN,7.95,7.82,7.72,7.95,237.9,NaN,265.3,201.3,158.8,143.7,7.046581,2.416452,3.806452,3.419355,2.903226,3.566667,6.516129,3.096774,2.524138,5.383871,9.003226,70.129032,537.125806,22.203226,27.816129,16.912903,171.696774
2015-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.178964,2.267500,1.035714,0.821429,0.321429,0.500000,0.714286,0.464286,0.111111,5.453571,10.032143,66.535714,537.521429,22.771429,28.982143,16.950000,173.585714
2015-03-31,332.0,NaN,81.0,396.0,431.0,414.0,0.49,NaN,0.77,0.94,0.89,0.94,0.020,NaN,0.060,0.43,0.26,0.44,0.0160,NaN,0.0160,0.0160,0.0160,0.0160,0.030,NaN,0.100,0.010,0.010,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.80,NaN,7.40,14.0,15.00,12.00,25.4,NaN,23.1,24.2,26.3,26.4,6.68,NaN,6.58,6.25,6.59,6.82,1.40,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.19,NaN,7.97,8.11,7.88,8.02,324.1,NaN,375.1,212.4,205.6,201.8,0.379903,2.235484,0.741935,1.225806,0.548387,0.580645,0.935484,2.354839,2.419355,3.909677,8.503226,70.838710,424.948387,20.938710,27.403226,15.422581,144.261290
2015-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.367200,2.231667,0.600000,1.033333,0.758621,0.357143,1.200000,1.333333,1.310345,2.890000,8.410000,65.866667,343.363333,18.086667,25.480000,11.866667,157.293333
2015-05-31,292.0,NaN,81.0,340.0,331.0,383.0,0.80,NaN,0.46,1.24,1.25,1.25,0.062,NaN,0.053,0.72,0.71,0.68,0.0160,NaN,0.0160,0.0160,0.0160,0.0160,0.010,NaN,0.010,0.010,0.010,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.10,NaN,30.00,28.0,29.00,25.00,18.9,NaN,17.2,18.1,18.2,18.7,8.46,NaN,8.64,8.39,8.95,9.05,1.20,NaN,1.20,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.6,1.90,8.18,NaN,7.89,7.96,7.99,8.05,443.5,NaN,371.4,257.9,224.8,203.1,0.433161,2.241935,1.322581,0.748387,0.300000,0.344828,0.774194,0.548387,0.325806,1.525806,5.838710,74.193548,220.129032,14.974194,21.283871,9.674194,129.987097
2015-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.464500,2.244000,0.866667,0.903333,0.241379,0.285714,0.633333,0.413793,0.348276,1.213333,5.570000,71.733333,186.963333,11.646667,17.843333,5.803333,158.573333
2015-07-31,132.0,NaN,12.0,233.0,289.0,312.0,0.60,NaN,1.10,0.99,1.14,1.11,0.100,NaN,0.074,0.30,0.63,0.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.20,NaN,60.00,12.0,26.00,27.00,9.8,NaN,8.4,11.1,11.2,11.6,8.85,NaN,8.55,9.05,7.95,7.93,0.60,NaN,0.90,NaN,NaN,NaN,NaN,NaN,NaN,20.2,2.0,0.70,8.78,NaN,8.06,8.61,8.15,8.00,389.0,NaN,327.1,327.9,239.7,222.4,0.582774,2.251290,0.387097,1.151613,1.275862,0.935484,0.096774,1.774194,1.000000,1.077419,5.441935,76.258065,196.616129,10.577419,17.158065,5.054839,149.638710
2015-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.399821,2.962857,11.903226,9.580645,7.586207,8.344828,8.354839,10.333333,10.677419,1.848387,4.161290,78.258065,215.738710,14.074194,18.874194,9.903226,192.787097
2015-09-30,231.0,NaN,104.0,437.0,477.0,434.0,1.06,NaN,0.73,1.63,1.67,1.69,0.310,NaN,0.110,0.63,0.66,0.76,0.0160,NaN,0.0160,0.0160,0.0160,0.0160,0.010,NaN,0.030,0.010,0.010,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.00,NaN,16.00,25.0,24.00,24.00,15.2,NaN,14.8,15.3,15.4,14.9,8.81,NaN,8.83,8.73,9.07,8.52,1.70,NaN,1.30,NaN,NaN,NaN,NaN,NaN,NaN,0.9,2.6,0.40,8.36,NaN,8.55,8.42,8.19,8.20,274.8,NaN,286.5,191.5,164.6,144.3,3.845000,2.350000,2.200000,2.566667,0.724138,2.035714,2.366667,1.000000,0.703333,2.703333,6.900000,68.366667,346.883333,12.203333,17.736667,6.993333,197.540000
2015-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.096774,3.248387,3.800000,3.354839,3.225806,3.193548,2.645161,3.477419,6.612903,72.419355,403.951613,14.238710,18.951613,9.858065,224.861290
2015-11-30,288.0,309.0,93.0,373.0,390.0,292.0,0.96,1.06,0.71,1.13,1.13,1.16,0.170,0.360,0.100,0.46,0.44,0.49,0.0230,0.0230,0.0230,0.0230,0.0230,0.0230,0.140,0.030,0.110,0.010,0.010,0.270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.50,5.50,9.20,23.0,22.00,22.00,21.8,22.0,21.6,21.4,21.7,21.9,7.76,7.45,7.69,8.24,8.10,8.00,3.10,3.00,2.80,NaN,NaN,NaN,NaN,3.00,NaN,3.7,2.7,1.50,7.83,7.87,7.69,7.80,7.84,7.84,336.2,344.8,315.0,192.6,188.3,184.7,0.960765,2.264444,2.166667,1.310345,1.500000,1.310345,1.166667,2.310345,2.241379,4.880000,8.923333,65.866667,524.113333,18.110000,24.130000,12.196667,191.423333
2015-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.376258,2.562903,6.354839,6.722581,3.300000,5.566667,6.733333,4.645161,3.583871,5.709677,10.025806,65.387097,580.425806,21.829032,27.858065,15.638710,157.587097
2016-01-31,296.0,547.0,110.0,522.0,523.0,536.0,0.75,1.43,0.86,1.18,1.22,1.27,0.079,0.550,0.076,0.49,0.42,0.78,0.0190,0.0190,0.0190,0.0190,0.0190,0.0190,0.010,0.010,0.010,0.010,0.010,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,9.40,12.00,14.0,17.00,13.00,26.2,25.8,24.2,26.3,26.3,26.9,6.97,6.48,7.39,7.45,7.99,7.42,0.50,0.50,0.90,NaN,NaN,NaN,NaN,3.60,NaN,1.5,3.3,7.10,7.99,8.10,7.98,7.49,7.88,7.40,243.2,266.9,168.2,166.6,176.2,165.4,11.075065,2.416452,0.000000,0.354839,0.000000,0.233333,0.000000,0.161290,0.325806,6.058065,10.322581,65.225806,582.680645,23.422581,29.816129,17.238710,169.987097
2016-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.633724,2.242069,1.965517,3.862069,2.321429,2.964286,3.241379,3.034483,2.714286,5.631034,9.627586,65.689655,522.537931,24.120690,30.406897,18.137931,177.637931

In [42]:
# Se obtiene un dataset mensual de extremos de caudal a partir del dataset crudo

dinagua_mensual_extremos_crudo = (
    data_dinagua_crudo[[('Caudal (Q) [m3/s]', 'Florida (Puente Ruta 5)')]]
    .resample('ME')
    .agg(['max', 'min'])
)

# Se ajusta el índice al último día de cada mes
dinagua_mensual_extremos_crudo.index = dinagua_mensual_extremos_crudo.index.to_period('M').to_timestamp('M')

dinagua_mensual_extremos_crudo.columns = [
    'Caudal Maximo (Qmax) [m3/s] Florida (Puente Ruta 5)',
    'Caudal Minimo (Qmin) [m3/s] Florida (Puente Ruta 5)'
]

# Se selecciona el intervalo de trabajo
dinagua_mensual_extremos_crudo = dinagua_mensual_extremos_crudo.loc["2014-01-01":"2022-12-31"]

dinagua_mensual_extremos_crudo.head()

,Caudal Maximo (Qmax) [m3/s] Florida (Puente Ruta 5),Caudal Minimo (Qmin) [m3/s] Florida (Puente Ruta 5)
date,,
2014-01-31,73.353,0.466
2014-02-28,477.531,8.256
2014-03-31,28.279,2.004
2014-04-30,1065.991,0.035
2014-05-31,67.891,0.053

In [43]:
# Se obtiene un dataset mensual de precipitaciones máximas a partir del dataset crudo

inumet_mensual_extremos_crudo = (
    data_inumet_crudo
    .resample('ME')
    .max()
)

# Se ajusta el índice al último día de cada mes
inumet_mensual_extremos_crudo.index = inumet_mensual_extremos_crudo.index.to_period('M').to_timestamp('M')

inumet_mensual_extremos_crudo.columns = [
    f'Precipitacion maxima (Pmax) [mm] {station}'
    for variable, station in inumet_mensual_extremos_crudo.columns
]

# Se selecciona el intervalo de trabajo
inumet_mensual_extremos_crudo = inumet_mensual_extremos_crudo.loc["2014-01-01":"2022-12-31"]

inumet_mensual_extremos_crudo.head()

,Precipitacion maxima (Pmax) [mm] Cerro Colorado,Precipitacion maxima (Pmax) [mm] La Cruz,Precipitacion maxima (Pmax) [mm] Mendoza,Precipitacion maxima (Pmax) [mm] San Gabriel,Precipitacion maxima (Pmax) [mm] Sarandi Grande,Precipitacion maxima (Pmax) [mm] Villa 25 de Mayo,Precipitacion maxima (Pmax) [mm] Villa Cardal
date,,,,,,,
2014-01-31,45.0,51.0,68.0,55.0,47.0,80.0,105.0
2014-02-28,57.0,54.0,56.0,45.0,70.0,42.0,55.0
2014-03-31,26.0,23.0,35.0,26.0,29.0,30.0,30.0
2014-04-30,86.0,64.0,45.0,55.0,62.0,55.0,50.0
2014-05-31,27.0,24.0,35.0,22.0,28.0,25.0,54.0

In [44]:
# Se asegura que todos los sets tengan el mismo índice de fecha

dataset_completo_crudo.index = pd.to_datetime(dataset_completo_crudo.index)
dinagua_mensual_extremos_crudo.index = pd.to_datetime(dinagua_mensual_extremos_crudo.index)
inumet_mensual_extremos_crudo.index = pd.to_datetime(inumet_mensual_extremos_crudo.index)

# Se combinan los datasets
dataset_completo_crudo = pd.concat(
    [
        dataset_completo_crudo,
        dinagua_mensual_extremos_crudo,
        inumet_mensual_extremos_crudo
    ],
    axis=1
)

dataset_completo_crudo.head()

,Fósforo Total (PT) [μg/L] XSLH020,Fósforo Total (PT) [μg/L] XSLH030,Fósforo Total (PT) [μg/L] XSLH010,Fósforo Total (PT) [μg/L] EPSE030,Fósforo Total (PT) [μg/L] EPSE040,Fósforo Total (PT) [μg/L] EPSE020,Nitrógeno Total (NT) [mg/L] XSLH020,Nitrógeno Total (NT) [mg/L] XSLH030,Nitrógeno Total (NT) [mg/L] XSLH010,Nitrógeno Total (NT) [mg/L] EPSE030,Nitrógeno Total (NT) [mg/L] EPSE040,Nitrógeno Total (NT) [mg/L] EPSE020,Ion Nitrato (NO3-) [mg/L] XSLH020,Ion Nitrato (NO3-) [mg/L] XSLH030,Ion Nitrato (NO3-) [mg/L] XSLH010,Ion Nitrato (NO3-) [mg/L] EPSE030,Ion Nitrato (NO3-) [mg/L] EPSE040,Ion Nitrato (NO3-) [mg/L] EPSE020,Ion Nitrito (NO2-) [mg/L] XSLH020,Ion Nitrito (NO2-) [mg/L] XSLH030,Ion Nitrito (NO2-) [mg/L] XSLH010,Ion Nitrito (NO2-) [mg/L] EPSE030,Ion Nitrito (NO2-) [mg/L] EPSE040,Ion Nitrito (NO2-) [mg/L] EPSE020,Ion Amonio (NH4+) [mg/L] XSLH020,Ion Amonio (NH4+) [mg/L] XSLH030,Ion Amonio (NH4+) [mg/L] XSLH010,Ion Amonio (NH4+) [mg/L] EPSE030,Ion Amonio (NH4+) [mg/L] EPSE040,Ion Amonio (NH4+) [mg/L] EPSE020,Ion Fosfato (PO4-) [µg/L] XSLH020,Ion Fosfato (PO4-) [µg/L] XSLH030,Ion Fosfato (PO4-) [µg/L] XSLH010,Ion Fosfato (PO4-) [µg/L] EPSE030,Ion Fosfato (PO4-) [µg/L] EPSE040,Ion Fosfato (PO4-) [µg/L] EPSE020,Glifosato [µg/L] XSLH020,Glifosato [µg/L] XSLH030,Glifosato [µg/L] XSLH010,Glifosato [µg/L] EPSE030,Glifosato [µg/L] EPSE040,Glifosato [µg/L] EPSE020,Solidos totales (ST) [mg/L] XSLH020,Solidos totales (ST) [mg/L] XSLH030,Solidos totales (ST) [mg/L] XSLH010,Solidos totales (ST) [mg/L] EPSE030,Solidos totales (ST) [mg/L] EPSE040,Solidos totales (ST) [mg/L] EPSE020,Solidos suspendidos totales (SST) [mg/L] XSLH020,Solidos suspendidos totales (SST) [mg/L] XSLH030,Solidos suspendidos totales (SST) [mg/L] XSLH010,Solidos suspendidos totales (SST) [mg/L] EPSE030,Solidos suspendidos totales (SST) [mg/L] EPSE040,Solidos suspendidos totales (SST) [mg/L] EPSE020,Turbidez [NTU] XSLH020,Turbidez [NTU] XSLH030,Turbidez [NTU] XSLH010,Turbidez [NTU] EPSE030,Turbidez [NTU] EPSE040,Turbidez [NTU] EPSE020,Temperatura del agua (T) [ºC] XSLH020,Temperatura del agua (T) [ºC] XSLH030,Temperatura del agua (T) [ºC] XSLH010,Temperatura del agua (T) [ºC] EPSE030,Temperatura del agua (T) [ºC] EPSE040,Temperatura del agua (T) [ºC] EPSE020,Oxigeno Disuelto (OD) [mg/L] XSLH020,Oxigeno Disuelto (OD) [mg/L] XSLH030,Oxigeno Disuelto (OD) [mg/L] XSLH010,Oxigeno Disuelto (OD) [mg/L] EPSE030,Oxigeno Disuelto (OD) [mg/L] EPSE040,Oxigeno Disuelto (OD) [mg/L] EPSE020,Demanda Bioquímica de Oxigeno (DBO) [mg/L] XSLH020,Demanda Bioquímica de Oxigeno (DBO) [mg/L] XSLH030,Demanda Bioquímica de Oxigeno (DBO) [mg/L] XSLH010,Demanda Bioquímica de Oxigeno (DBO) [mg/L] EPSE030,Demanda Bioquímica de Oxigeno (DBO) [mg/L] EPSE040,Demanda Bioquímica de Oxigeno (DBO) [mg/L] EPSE020,Clorofila-a (Chl-a) [μg/L] XSLH020,Clorofila-a (Chl-a) [μg/L] XSLH030,Clorofila-a (Chl-a) [μg/L] XSLH010,Clorofila-a (Chl-a) [μg/L] EPSE030,Clorofila-a (Chl-a) [μg/L] EPSE040,Clorofila-a (Chl-a) [μg/L] EPSE020,Potencial de Hidrogeno (pH) [NA] XSLH020,Potencial de Hidrogeno (pH) [NA] XSLH030,Potencial de Hidrogeno (pH) [NA] XSLH010,Potencial de Hidrogeno (pH) [NA] EPSE030,Potencial de Hidrogeno (pH) [NA] EPSE040,Potencial de Hidrogeno (pH) [NA] EPSE020,Conductividad [μS/cm] XSLH020,Conductividad [μS/cm] XSLH030,Conductividad [μS/cm] XSLH010,Conductividad [μS/cm] EPSE030,Conductividad [μS/cm] EPSE040,Conductividad [μS/cm] EPSE020,Caudal (Q) [m3/s] Florida (Puente Ruta 5),Nivel de agua (h) [m] Florida (Puente Ruta 5),Precipitacion (P) [mm] Cerro Colorado,Precipitacion (P) [mm] La Cruz,Precipitacion (P) [mm] Mendoza,Precipitacion (P) [mm] San Gabriel,Precipitacion (P) [mm] Sarandi Grande,Precipitacion (P) [mm] Villa 25 de Mayo,Precipitacion (P) [mm] Villa Cardal,Evapotranspiracion Penman (ET) [mm] INIA Las Brujas,Heliofania (Hel) [hs] INIA Las Brujas,Humedad relativa media (HR) [%] INIA Las Brujas,Radiacion solar (RS) [cal/cm2/dia] INIA Las Brujas,Temperatura del aire media (TA) [ºC(24hs)] INIA Las Brujas,Temperatura del aire maxima (TA) [ºC] INIA Las Brujas,Temperatura del aire minima (TA) [ºC] INIA Las Brujas,Velocidad del viento (VV) [2m/km/24h] INIA Las Brujas,Caudal Maximo (Qmax) [m3/s] Florida (Puente Ruta 5),Caudal Minimo (Qmin) [m3/s] Florida (Puente Ruta 5),Precipitacion maxima (Pmax) [mm] Cerro Colorado,Precipitacion maxima (Pmax) [mm] La Cruz,Precipitacion maxima (Pmax) [mm] Mendoza,Precipitacion maxima (Pmax) [mm] San Gabriel,Precipitacion maxima (Pmax) [mm] Sarandi Grande,Precipitacion maxima (Pmax) [mm] Villa 25 de Mayo,Precipitacion maxima (Pmax) [mm] Villa Cardal
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-31,351.0,475.0,181.0,456.0,474.0,505.0,1.18,2.37,1.07,1.44,1.51,1.83,0.27,0.87,0.18,0.72,0.72,0.92,0.0450,0.2100,0.0200,0.016,0.020,0.0160,0.070,0.160,0.04,0.05,0.070,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,5.7,12.0,8.3,8.8,11.0,26.9,26.8,25.5,27.2,27.4,26.6,5.48,3.60,5.65,6.72,6.48,5.94,0.8,1.2,1.1,NaN,NaN,NaN,NaN,4.40,NaN,0.7,0.5,0.3,7.58,7.49,7.50,7.93,7.69,7.63,239.1,301.2,234.5,239.8,240.9,240.6,12.228097,2.535161,9.677419,7.000000,8.225806,7.935484,7.193548,8.366667,11.433333,5.506452,8.529032,67.645161,521.180645,23.329032,28.854839,17.783871,162.916129,73.353,0.466,45.0,51.0,68.0,55.0,47.0,80.0,105.0
2014-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.725571,3.562500,12.500000,8.042857,8.814815,7.285714,9.892857,8.000000,9.117857,4.060714,6.560714,76.500000,421.378571,21.425000,26.421429,17.607143,140.932143,477.531,8.256,57.0,54.0,56.0,45.0,70.0,42.0,55.0
2014-03-31,420.0,210.0,78.0,400.0,390.0,390.0,1.08,0.99,0.96,1.28,1.26,1.34,0.16,0.34,0.10,0.51,0.54,0.54,0.0029,0.0065,0.0029,NaN,0.014,0.0012,0.041,0.043,0.02,0.03,0.014,0.013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,13.0,18.0,19.0,15.0,15.0,18.8,19.7,18.7,21.9,22.1,22.4,7.88,7.48,7.18,7.03,7.04,6.51,2.7,1.7,1.7,NaN,NaN,NaN,NaN,0.40,NaN,0.4,0.1,0.1,7.63,7.83,7.65,7.57,7.61,7.70,191.0,204.6,146.4,182.9,154.5,142.8,7.386935,2.451290,2.645161,3.161290,2.965517,3.133333,3.806452,3.290323,3.400000,3.638710,7.867742,71.193548,405.835484,19.058065,24.693548,13.783871,169.254839,28.279,2.004,26.0,23.0,35.0,26.0,29.0,30.0,30.0
2014-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.504200,2.677333,4.366667,4.900000,3.827586,4.433333,4.266667,5.500000,4.655172,2.203333,6.710000,76.133333,298.750000,16.613333,22.150000,11.930000,148.876667,1065.991,0.035,86.0,64.0,45.0,55.0,62.0,55.0,50.0
2014-05-31,198.0,202.0,117.0,389.0,361.0,340.0,1.29,1.02,1.42,1.29,1.25,1.28,0.55,0.60,0.88,0.60,0.52,0.61,0.0160,0.0160,0.0160,0.016,0.016,0.0160,0.060,0.080,0.27,0.01,0.010,0.050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,15.0,18.0,25.0,26.0,25.0,17.0,17.4,17.2,18.0,18.0,17.9,8.35,8.06,NaN,7.10,6.71,7.14,2.6,3.4,6.2,NaN,NaN,NaN,NaN,0.05,NaN,0.4,0.4,0.7,7.49,7.34,7.41,7.35,7.30,7.22,173.6,187.3,143.7,104.6,95.5,132.3,14.999000,2.522903,3.451613,3.441935,2.666667,3.310345,3.322581,3.129032,3.666667,1.138710,4.200000,81.677419,185.232258,12.948387,17.748387,8.906452,127.487097,67.891,0.053,27.0,24.0,35.0,22.0,28.0,25.0,54.0

In [45]:
# Obviamente, al tratarse de un dataset crudo hay NaN en prácticamente todas las columnas (por ejemplo, los datos de calidad son bimensuales)
# No se eliminan las columnas con NaN!

# Se guarda el dataset de trabajo en un archivo .parquet

dataset_completo_crudo.to_parquet('./0-Datasets/dataset_completo_crudo.parquet')